# Artificial Neural Network

### Importing the libraries

In [72]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [73]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [74]:
dataset = pd.read_csv("Churn_Modelling.csv")
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [75]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [76]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

In [77]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

Label Encoding the "Gender" column

In [78]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [("encoder", OneHotEncoder(), [1])], remainder = "passthrough")
X = np.array(ct.fit_transform(X))

In [80]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [82]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler().fit(X_train)
# feature scaling is must for all fetures (columns)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [83]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [84]:
# units = 6 : from experimenting with deferent numbers
# units = 6 : first hidden layer with 6 neurons
# activation = "relu" : Rectifier activation function
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the second hidden layer

In [85]:
ann.add(tf.keras.layers.Dense(units = 6, activation = "relu"))

### Adding the output layer

In [86]:
# units = 2 : dataset have binary dependent variable (0 or 1) we only need one neurons
# if dataset have n number of classes in dependent variable we need n neurons
# activation = "sigmoid" : Sigmoid activation function
# softmax for catogorical out
# this can give probabilities of predictions
ann.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

## Part 3 - Training the ANN

### Compiling the ANN

In [87]:
# optimizer = "adam" : optimizer for perform stochastic gradient descent
# loss = "binary_crossentropy" : if the prediction is binary this is the loss
# compute the deference between predication and the real result
# categorical_crossentropy for catogorical out
# metrics=["accuracy"] : evaluation matrix (accuracy matrix)
ann.compile(optimizer = "adam", loss = "binary_crossentropy", metrics=["accuracy"])

### Training the ANN on the Training set

In [88]:
# batch_size = 32 : batch learning (32 default)
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5687 - accuracy: 0.7769
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4729 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4428 - accuracy: 0.8016
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4294 - accuracy: 0.8065
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4208 - accuracy: 0.8094
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4123 - accuracy: 0.8148
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4025 - accuracy: 0.8235
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.8326
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3815 - accuracy: 0.8414
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3715 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [98]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

[[0.02764508]]


In [99]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [112]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [113]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 200  205]]


0.86